# Numpy
- Numpy (short for Numerical Pyhton) is a powerful open-source library n python used for numerical comuting.Its one of the core building bloks for data science, machine learning, generative AI and Agentic AI..etc.

### what numpy does?
- multi-dimensional array
- Fast arrays: A special data structure called an  ndarray(n-dimensional array) that stores numbers efficiently.
- Mathematical operations: Funcations for performaing calculations like addition, mulitplication,trignometry,stats  -- often much fater than plain python
- Linear algebra tools: matrix operations,eigenvalues, dot products etc. 
- Random number generation:used for simulations and ML

### Why its important
- Speed: Numpy is implemented in optimised C code, so it runs much faster than a regular python loops
- Convenience: You can perform operations on entire arrays without writing loops.
- Foundation for other libraries. Many popular tools like Pandas, Matplotlib, and scikit-learn are built on top of Numpy
- Handling numerical data inside agents
- working with emdeddings(vectors)
- Doing similarity calculations(cosine similarty etc)
- supporting backend computations when needed


In [ ]:
# pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
mylist = [1,2,3,2]
print(mylist)
print(type(mylist))

[1, 2, 3, 2]
<class 'list'>


In [6]:
myarray = np.array(mylist)
print(myarray)
print(type(myarray))

[1 2 3 2]
<class 'numpy.ndarray'>


In [7]:
array =np.array([1,2,3,4,5])
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
array =np.array([[1,2,3],[4,5,6]])
print(array)
print(type(array))
print("Shape of the array is :", array.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
Shape of the array is : (2, 3)


In [14]:
array = np.zeros((3,4))
print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
array = np.zeros((3,4),dtype=int)
print(array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [16]:
array = np.ones((3,4),dtype=int)
print(array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [18]:
array = np.full((3,4),5,dtype=int)
print(array)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [34]:
array = np.random.random((3,4))   ## this will generate 38*4 array with random values
print(array)
print(array[0,0])   # to print first row of the first column
print()
print(array[0,1])   # to print first row of the second column
print()
print(array> 0.2)   # this will return True for all the values >0.2 in the array
print()
print(array[array> 0.2]) # this will return a new array only the values greater than 0.2
print()
print(np.sum(array))  # This will sum all values in the array
print()
print(np.floor(array))  
print()
print(np.ceil(array))
print()
print(np.round(array))
                        

[[0.67136231 0.90193148 0.32814062 0.33280635]
 [0.29796301 0.53816516 0.53517628 0.07952642]
 [0.87240929 0.67163101 0.53862097 0.86709109]]
0.6713623069313779

0.9019314797454444

[[ True  True  True  True]
 [ True  True  True False]
 [ True  True  True  True]]

[0.67136231 0.90193148 0.32814062 0.33280635 0.29796301 0.53816516
 0.53517628 0.87240929 0.67163101 0.53862097 0.86709109]

6.634823990874644

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1. 1. 0. 0.]
 [0. 1. 1. 0.]
 [1. 1. 1. 1.]]


In [38]:
first  = np.array([1,2,3])
second = np.array([1,2,3])
print(first+second)
print(first*second)
print(first+2)
print(first*2)

[2 4 6]
[1 4 9]
[3 4 5]
[2 4 6]


In [41]:
print(np.__version__)

2.4.6


In [40]:
dimension_inch = np.array([1,2,3])
dimension_cm = dimension_inch*2.54
print(dimension_cm)

[2.54 5.08 7.62]


### Create a NumPy ndarray Object
- NumPy is used to work with arrays. The array object in NumPy is called ndarray.

- We can create a NumPy ndarray object by using the array() function.

In [42]:
arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


---

- To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [43]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)
print(arr.shape)

[1 2 3 4 5]
(5,)


In [45]:
# 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
arr = np.array(42)
print(arr)
print(arr.shape)

42
()


In [47]:
# 1-D array
# An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

arr = np.array([1,2,3,4,5])
print(arr)
print(arr.shape)

[1 2 3 4 5]
(5,)


In [ ]:
# 2-D array
# An array that has 1-D arrays as its elements is called a 2-D array.
# These are often used to represent matrix or 2nd order tensors.

arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr)
print(arr.shape)

[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)


In [51]:
#n3-D arrays
# An array that has 2-D arrays (matrices) as its elements is called 3-D array.
# These are often used to represent a 3rd order tensor.

arr= np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
print(arr.shape)



[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)


In [52]:
# check number of dimensions
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


---

- Higher Dimensional Arrays
- An array can have any number of dimensions.

- When the array is created, you can define the number of dimensions by using the ndmin argument.

In [54]:
# Create an array with 5 dimensions and verify that it has 5 dimensions:

arr = np.array([1,2,3],ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3]]]]]
number of dimensions : 5


---

#### NumPy Array Indexing


- Access Array Elements: -
- Array indexing is the same as accessing an array element.

- You can access an array element by referring to its index number.

- The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [57]:
arr = np.array([1,2,3])
print(arr[0])
print(arr[2])

1
3


In [59]:
# Get third and fourth elements from the following array and add them.
arr = np.array([1,2,3,4])
print(arr[2] + arr[3])



7


##### Access 2-D Arrays
- To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

- Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [67]:
arr =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.ndim)
print('2nd element on 1st row: ', arr[0, 1])
print('3rd element on 2nd row: ', arr[1, 2])

print('Access the element on the 2nd row, 5th column:', arr[1,4]) 

2
2nd element on 1st row:  2
3rd element on 2nd row:  8
Access the element on the 2nd row, 5th column: 10


##### Access 3-D Arrays
-To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [74]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


print(arr)
print(arr[0, 1, 2])
print(arr[1,0,2])
print(arr[1,1,0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6
9
10


#### Negative Indexing
- Use negative indexing to access an array from the end.

In [79]:
# Print the last element from the 2nd dim:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[-1,-1])
print(arr[1,-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10
10


### NumPy Array Slicing

- Slicing in python means taking elements from one given index to another given index.
- We pass slice instead of index like this: [start:end].
- We can also define the step, like this: [start:end:step].
- If we don't pass start its considered 0
- If we don't pass end its considered length of array in that dimension
- If we don't pass step its considered 1

In [86]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

#Slice elements from index 4 to the end of the array:
print(arr[4:])

# Slice elements from the beginning to index 4 (not included):
print(arr[:4])


## Negative Slicing
# Slice from the index 3 from the end to index 1 from the end:
print(arr[-3:-1])


[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]


### Slicing 2-D Arrays


In [99]:
# From the second element, slice elements from index 1 to index 4 (not included):
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[1,1:4])

# From both elements, return index 2:
print(arr[0:2,2])

#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
print(arr[0:2,1:4])




[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


---

## NumPy Data Types
- By default Python have these data types:

- strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
- integer - used to represent integer numbers. e.g. -1, -2, -3
- float - used to represent real numbers. e.g. 1.2, 42.42
- boolean - used to represent True or False.
- complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

##### NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

- Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

- Checking the Data Type of an Array
- The NumPy array object has a property called dtype that returns the data type of the array:

In [105]:
arr1 = np.array([1, 2, 3, 4])
print(arr1.dtype)
arr2 = np.array([1.0, 2.0, 3.0, 4.0])
print(arr2.dtype)
arr3 = np.array(['apple', 'banana', 'cherry'])
print(arr3.dtype)
arr4 = np.array(('Apple','Mango','grapes'))
print(arr4.dtype)

int64
float64
<U6
<U6


##### Creating Arrays With a Defined Data Type
- We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

- dtype --> 	Meaning
- 'i'	-->   integer
- 'f'	-->   float32
- 'F'	-->   complex64
- 'U'	-->   Unicode string
- bool	-->   True/False

-- For i, u, f, S and U we can define size as well.



In [106]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [109]:
arr = np.array([1,2,3,4],dtype='F')
print(arr)
print(arr.dtype)
print()
arr = np.array([1,2,3,4],dtype='f')
print(arr)
print(arr.dtype)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex64

[1. 2. 3. 4.]
float32


In [112]:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

print()
arr = np.array([1, 2, 3, 4], dtype='i')
print(arr)
print(arr.dtype)


[1 2 3 4]
int32

[1 2 3 4]
int32


#### Converting Data Type on Existing Arrays
- The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

- The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

- The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

